# Generated by Django 5.1.4 on 2025-03-09 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_dishingredient_alter_dish_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='ingredients',
        ),
    ]
